#!/usr/bin/env bash
set -Eeuo pipefail

cd "${HOME:-/home/container}"
SERVER_ROOT="$(pwd)"
PORT="${1:-${SERVER_PORT:-27015}}"

log() {
  printf '[gmod-egg] %s\n' "$*"
}

sync_steamclient() {
  mkdir -p "$SERVER_ROOT/.steam/sdk32" "$SERVER_ROOT/.steam/sdk64"
  if [[ -f "$SERVER_ROOT/steamcmd/linux32/steamclient.so" ]]; then
    cp -f "$SERVER_ROOT/steamcmd/linux32/steamclient.so" "$SERVER_ROOT/.steam/sdk32/steamclient.so"
  fi
  if [[ -f "$SERVER_ROOT/steamcmd/linux64/steamclient.so" ]]; then
    cp -f "$SERVER_ROOT/steamcmd/linux64/steamclient.so" "$SERVER_ROOT/.steam/sdk64/steamclient.so"
  fi
}

steam_update() {
  [[ "${GMOD_AUTO_UPDATE:-1}" == "1" ]] || return 0
  [[ -x "$SERVER_ROOT/steamcmd/steamcmd.sh" ]] || {
    log "SteamCMD is missing; skipping automatic update."
    return 0
  }

  local -a cmd
  cmd=(
    "$SERVER_ROOT/steamcmd/steamcmd.sh"
    +force_install_dir "$SERVER_ROOT"
    +login anonymous
    +app_update "${SRCDS_APPID:-4020}"
  )

  if [[ -n "${SRCDS_BETAID:-}" ]]; then
    cmd+=( -beta "$SRCDS_BETAID" )
  fi

  if [[ "${VALIDATE_FILES:-0}" == "1" ]]; then
    cmd+=( validate )
  fi

  cmd+=( +quit )

  log "Checking Garry's Mod server files for updates..."
  "${cmd[@]}"
  sync_steamclient
}

cfg_escape() {
  local value="${1:-}"
  value="${value//$'\r'/}"
  value="${value//$'\n'/ }"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

write_panel_cfg() {
  mkdir -p "$SERVER_ROOT/garrysmod/cfg"

  local hostname password rcon location fastdl loading
  hostname="$(cfg_escape "${SERVER_NAME:-Pterodactyl GMod}")"
  password="$(cfg_escape "${SERVER_PASSWORD:-}")"
  rcon="$(cfg_escape "${RCON_PASSWORD:-}")"
  location="$(cfg_escape "${SERVER_LOCATION:-eu}")"
  fastdl="$(cfg_escape "${FASTDL_URL:-}")"
  loading="$(cfg_escape "${LOADING_URL:-}")"

  cat > "$SERVER_ROOT/garrysmod/cfg/pterodactyl.cfg" <<CFG
// Generated by the Pterodactyl Garry's Mod Ultimate egg on every start.
// Put your own persistent settings in garrysmod/cfg/server.cfg.
hostname "${hostname}"
sv_password "${password}"
rcon_password "${rcon}"
sv_location "${location}"
hide_server "${HIDE_SERVER:-0}"
sv_lan "${SV_LAN:-0}"
host_workshop_autoupdate "${WORKSHOP_AUTO_UPDATE:-1}"
sv_downloadurl "${fastdl}"
sv_loadingurl "${loading}"
exec banned_ip.cfg
exec banned_user.cfg
CFG
}

steam_update
write_panel_cfg
sync_steamclient

BIN="${SERVER_BINARY:-srcds_run}"
if [[ ! -x "$SERVER_ROOT/$BIN" ]]; then
  if [[ "$BIN" == "srcds_run_x64" && -x "$SERVER_ROOT/srcds_run" ]]; then
    log "srcds_run_x64 was requested but is unavailable; falling back to srcds_run."
    BIN="srcds_run"
  else
    log "Server binary '$BIN' does not exist or is not executable."
    exit 1
  fi
fi

ARGS=(
  -game garrysmod
  -console
  -port "$PORT"
  +ip 0.0.0.0
  -strictportbind
  -norestart
  +maxplayers "${MAX_PLAYERS:-32}"
  -tickrate "${TICKRATE:-33}"
  +exec pterodactyl.cfg
  +gamemode "${GAMEMODE:-sandbox}"
  +host_workshop_autoupdate "${WORKSHOP_AUTO_UPDATE:-1}"
)

if [[ -n "${WORKSHOP_ID:-}" ]]; then
  ARGS+=( +host_workshop_collection "$WORKSHOP_ID" )
fi

if [[ -n "${STEAM_TOKEN:-}" ]]; then
  ARGS+=( +sv_setsteamaccount "$STEAM_TOKEN" )
fi

if [[ "${LUA_REFRESH:-0}" != "1" ]]; then
  ARGS+=( -disableluarefresh )
fi

if [[ "${P2P_MODE:-0}" == "1" ]]; then
  ARGS+=( -p2p )
fi

ARGS+=( +map "${SRCDS_MAP:-gm_flatgrass}" )

if [[ -n "${CUSTOM_ARGS:-}" ]]; then
  read -r -a EXTRA_ARGS <<< "$CUSTOM_ARGS"
  ARGS+=( "${EXTRA_ARGS[@]}" )
fi

log "Starting Garry's Mod with $BIN"
exec "$SERVER_ROOT/$BIN" "${ARGS[@]}"
